//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class User : object
    {
        
        private System.Collections.Generic.List<ServiceReference1.Cart> CartsField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private System.Collections.Generic.List<ServiceReference1.Order> OrdersField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private System.Collections.Generic.List<ServiceReference1.Review> ReviewsField;
        
        private string ShippingAddressField;
        
        private int userIdField;
        
        private string userTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.Cart> Carts
        {
            get
            {
                return this.CartsField;
            }
            set
            {
                this.CartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.Order> Orders
        {
            get
            {
                return this.OrdersField;
            }
            set
            {
                this.OrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.Review> Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingAddress
        {
            get
            {
                return this.ShippingAddressField;
            }
            set
            {
                this.ShippingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Cart : object
    {
        
        private ServiceReference1.Product ProductField;
        
        private int QtyField;
        
        private ServiceReference1.User UserField;
        
        private int cartIdField;
        
        private System.Nullable<int> productIdField;
        
        private System.Nullable<int> userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cartId
        {
            get
            {
                return this.cartIdField;
            }
            set
            {
                this.cartIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Order : object
    {
        
        private System.DateTime DateField;
        
        private System.Collections.Generic.List<ServiceReference1.Invoice> InvoicesField;
        
        private System.Nullable<decimal> OrderTotalField;
        
        private System.Collections.Generic.List<ServiceReference1.PurchaseProduct> PurchaseProductsField;
        
        private string StatusField;
        
        private ServiceReference1.User UserField;
        
        private int orderIdField;
        
        private System.Nullable<int> userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.Invoice> Invoices
        {
            get
            {
                return this.InvoicesField;
            }
            set
            {
                this.InvoicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OrderTotal
        {
            get
            {
                return this.OrderTotalField;
            }
            set
            {
                this.OrderTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.PurchaseProduct> PurchaseProducts
        {
            get
            {
                return this.PurchaseProductsField;
            }
            set
            {
                this.PurchaseProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Review : object
    {
        
        private string MessageField;
        
        private ServiceReference1.Product ProductField;
        
        private System.Nullable<System.DateTime> ReviewDateField;
        
        private ServiceReference1.User UserField;
        
        private int ValueField;
        
        private System.Nullable<int> productIdField;
        
        private int reviewIdField;
        
        private System.Nullable<int> userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReviewDate
        {
            get
            {
                return this.ReviewDateField;
            }
            set
            {
                this.ReviewDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reviewId
        {
            get
            {
                return this.reviewIdField;
            }
            set
            {
                this.reviewIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Product : object
    {
        
        private System.Collections.Generic.List<ServiceReference1.Cart> CartsField;
        
        private string CategoryField;
        
        private string DescriptionField;
        
        private string ImageUrlField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private System.Collections.Generic.List<ServiceReference1.PurchaseProduct> PurchaseProductsField;
        
        private System.Collections.Generic.List<ServiceReference1.Review> ReviewsField;
        
        private System.Nullable<decimal> SalePriceField;
        
        private System.Nullable<int> StockQtyField;
        
        private bool isNewField;
        
        private bool onSaleField;
        
        private int productIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.Cart> Carts
        {
            get
            {
                return this.CartsField;
            }
            set
            {
                this.CartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.PurchaseProduct> PurchaseProducts
        {
            get
            {
                return this.PurchaseProductsField;
            }
            set
            {
                this.PurchaseProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference1.Review> Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalePrice
        {
            get
            {
                return this.SalePriceField;
            }
            set
            {
                this.SalePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StockQty
        {
            get
            {
                return this.StockQtyField;
            }
            set
            {
                this.StockQtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNew
        {
            get
            {
                return this.isNewField;
            }
            set
            {
                this.isNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool onSale
        {
            get
            {
                return this.onSaleField;
            }
            set
            {
                this.onSaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseProduct", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class PurchaseProduct : object
    {
        
        private ServiceReference1.Order OrderField;
        
        private ServiceReference1.Product ProductField;
        
        private int QtyField;
        
        private System.Nullable<int> orderIdField;
        
        private System.Nullable<int> productIdField;
        
        private int purchasedPIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Order Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int purchasedPId
        {
            get
            {
                return this.purchasedPIdField;
            }
            set
            {
                this.purchasedPIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Invoice : object
    {
        
        private System.Nullable<System.DateTime> DateField;
        
        private ServiceReference1.Order OrderField;
        
        private System.Nullable<bool> StatusField;
        
        private decimal TotalField;
        
        private int invoiceIdField;
        
        private System.Nullable<int> orderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Order Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int invoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebService")]
    public interface IWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Register", ReplyAction="http://tempuri.org/IWebService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Login", ReplyAction="http://tempuri.org/IWebService/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.User> LoginAsync(string logype, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/userExistence", ReplyAction="http://tempuri.org/IWebService/userExistenceResponse")]
        System.Threading.Tasks.Task<bool> userExistenceAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProducts", ReplyAction="http://tempuri.org/IWebService/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsOnSale", ReplyAction="http://tempuri.org/IWebService/GetProductsOnSaleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsOnSaleOnCategory", ReplyAction="http://tempuri.org/IWebService/GetProductsOnSaleOnCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleOnCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetFeaturedProducts", ReplyAction="http://tempuri.org/IWebService/GetFeaturedProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetFeaturedProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductByID", ReplyAction="http://tempuri.org/IWebService/GetProductByIDResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Product> GetProductByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsbyCategory", ReplyAction="http://tempuri.org/IWebService/GetProductsbyCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsbyCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCategories", ReplyAction="http://tempuri.org/IWebService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductbyName", ReplyAction="http://tempuri.org/IWebService/GetProductbyNameResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Product> GetProductbyNameAsync(string prod_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddToWishList", ReplyAction="http://tempuri.org/IWebService/AddToWishListResponse")]
        System.Threading.Tasks.Task AddToWishListAsync(int productId, int wishListId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddToCart", ReplyAction="http://tempuri.org/IWebService/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(int productId, int cartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetWishListItems", ReplyAction="http://tempuri.org/IWebService/GetWishListItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetWishListItemsAsync(int wishlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCart", ReplyAction="http://tempuri.org/IWebService/GetCartResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cart> GetCartAsync(int session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCartItems", ReplyAction="http://tempuri.org/IWebService/GetCartItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetCartItemsAsync(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/increaseQuantity", ReplyAction="http://tempuri.org/IWebService/increaseQuantityResponse")]
        System.Threading.Tasks.Task<bool> increaseQuantityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/decreaseQuantity", ReplyAction="http://tempuri.org/IWebService/decreaseQuantityResponse")]
        System.Threading.Tasks.Task<bool> decreaseQuantityAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/RemoveFromWishlist", ReplyAction="http://tempuri.org/IWebService/RemoveFromWishlistResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromWishlistAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/RemoveFromCart", ReplyAction="http://tempuri.org/IWebService/RemoveFromCartResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddProduct", ReplyAction="http://tempuri.org/IWebService/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/EditProduct", ReplyAction="http://tempuri.org/IWebService/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteProduct", ReplyAction="http://tempuri.org/IWebService/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTotalPrice", ReplyAction="http://tempuri.org/IWebService/GetTotalPriceResponse")]
        System.Threading.Tasks.Task<double> GetTotalPriceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PlaceOrder", ReplyAction="http://tempuri.org/IWebService/PlaceOrderResponse")]
        System.Threading.Tasks.Task<int> PlaceOrderAsync(ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GenerateInvoice", ReplyAction="http://tempuri.org/IWebService/GenerateInvoiceResponse")]
        System.Threading.Tasks.Task GenerateInvoiceAsync(ServiceReference1.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetSortedInvoices", ReplyAction="http://tempuri.org/IWebService/GetSortedInvoicesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Invoice>> GetSortedInvoicesAsync(int userId, string orderBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWebServiceChannel : ServiceReference1.IWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IWebService>, ServiceReference1.IWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceClient() : 
                base(WebServiceClient.GetDefaultBinding(), WebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), WebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(ServiceReference1.User user)
        {
            return base.Channel.RegisterAsync(user);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.User> LoginAsync(string logype, string password)
        {
            return base.Channel.LoginAsync(logype, password);
        }
        
        public System.Threading.Tasks.Task<bool> userExistenceAsync(string email)
        {
            return base.Channel.userExistenceAsync(email);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsAsync()
        {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleAsync()
        {
            return base.Channel.GetProductsOnSaleAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleOnCategoryAsync(string category)
        {
            return base.Channel.GetProductsOnSaleOnCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetFeaturedProductsAsync()
        {
            return base.Channel.GetFeaturedProductsAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Product> GetProductByIDAsync(int id)
        {
            return base.Channel.GetProductByIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsbyCategoryAsync(string category)
        {
            return base.Channel.GetProductsbyCategoryAsync(category);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Product> GetProductbyNameAsync(string prod_name)
        {
            return base.Channel.GetProductbyNameAsync(prod_name);
        }
        
        public System.Threading.Tasks.Task AddToWishListAsync(int productId, int wishListId)
        {
            return base.Channel.AddToWishListAsync(productId, wishListId);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(int productId, int cartID)
        {
            return base.Channel.AddToCartAsync(productId, cartID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetWishListItemsAsync(int wishlistId)
        {
            return base.Channel.GetWishListItemsAsync(wishlistId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cart> GetCartAsync(int session)
        {
            return base.Channel.GetCartAsync(session);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetCartItemsAsync(int cartId)
        {
            return base.Channel.GetCartItemsAsync(cartId);
        }
        
        public System.Threading.Tasks.Task<bool> increaseQuantityAsync(int id)
        {
            return base.Channel.increaseQuantityAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> decreaseQuantityAsync(int id)
        {
            return base.Channel.decreaseQuantityAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromWishlistAsync(int id)
        {
            return base.Channel.RemoveFromWishlistAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int id)
        {
            return base.Channel.RemoveFromCartAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(int productId)
        {
            return base.Channel.AddProductAsync(productId);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(int productId)
        {
            return base.Channel.EditProductAsync(productId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int productId)
        {
            return base.Channel.DeleteProductAsync(productId);
        }
        
        public System.Threading.Tasks.Task<double> GetTotalPriceAsync()
        {
            return base.Channel.GetTotalPriceAsync();
        }
        
        public System.Threading.Tasks.Task<int> PlaceOrderAsync(ServiceReference1.Order order)
        {
            return base.Channel.PlaceOrderAsync(order);
        }
        
        public System.Threading.Tasks.Task GenerateInvoiceAsync(ServiceReference1.Invoice invoice)
        {
            return base.Channel.GenerateInvoiceAsync(invoice);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Invoice>> GetSortedInvoicesAsync(int userId, string orderBy)
        {
            return base.Channel.GetSortedInvoicesAsync(userId, orderBy);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56432/WebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWebService,
        }
    }
}
